#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bodysnatcher'

if ARGV.count == 0
    puts "Please provide the URL to start on."
else
    walker = Bodysnatcher::Walker.new(ARGV[0])
    walker.walk
end
